### ISSUE TITLE
Amélioration - Dashboard AOM/opérateur/registre - bouton enregistrement des modifications des données de profil 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage-dashboard#18]
Dans le profil, on peut modifier les informations mais ce n'est pas clair si c'est automatiquement enregistré ou pas ==> ajouter un bouton enregistrer

![image](https://user-images.githubusercontent.com/15428433/52627387-806b8880-2eb5-11e9-9c26-9d5bca3c3f7e.png)

@samueleyre ou @nmrgt

**Comment by nmrgt** [comment]
Refaire le formulaire sans les formulaires dynamiques.

Estimation: 6h
