### ISSUE TITLE
Amélioration - Dashboard opérateur - Formulaire opérateur

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage-dashboard#19]
To @samueleyre and @nmrgt

Plusieurs problèmes :
* Pas de possibilité d'enregistrer de manière claire.
* La notification de champs obligatoires brouille la lisibilité ==> marquer comme optionnel le seul champs qui est optionnel. En effet le RNA n'est pas une donnée que l'ensemble des opérateurs a.
* Pas de lisibilité des différents types de données.

AVANT
![image](https://user-images.githubusercontent.com/15428433/52633725-97b27200-2ec5-11e9-91ac-24e4a8beacf9.png)

APRES
![image](https://user-images.githubusercontent.com/15428433/52633749-a6008e00-2ec5-11e9-9fad-c608261962e0.png)

D'ailleurs il faudra rajouter les informations suivantes également (à voir où le mettre) :
**Délégué à la protection des données** (lien vers un profil utilisateur)
NOM et Prénom
Email

**Responsable de traitement** (lien vers un profil utilisateur)
Nom et Prénom
Email

**Responsable technique** (lien vers un profil utilisateur)
Nom et Prénom
Email
Numéro de téléphone portable

**Comment by nmrgt** [comment]
Estimation : 8h

**Comment by margot-sanchez** [comment]
Presque parfait @nmrgt @samueleyre 
![image](https://user-images.githubusercontent.com/15428433/53356596-09f66e00-392c-11e9-84af-dc8d80423bae.png)
Cela doit être dans opérateur et non AOM :)

**Comment by margot-sanchez** [comment]
D'ailleurs en complément. Lorsque cela sera remis dans l'opérateur, cela serait logique de voir uniquement les utilisateurs de l'opérateur. A l'heure actuelle on peut définir comme CDO une personne de chez MaxiCovoite chez DédéCovoiturage
![image](https://user-images.githubusercontent.com/15428433/53740545-ba1c2780-3e94-11e9-8730-498e4f7968f3.png)

**Comment by margot-sanchez** [comment]
Bon finalement, il faut ces informations côté AOM & Opérateurs :)
