### ISSUE TITLE
Rajouter une page d'accueil

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage-dashboard#30]
Estimation : 3h

**Comment by margot-sanchez** [comment]
Voir modèles ici : https://docs.google.com/presentation/d/1Jvr0Uh9n3baZ56702xIX8SHlX--_FAR3xmRJm4iHXkg/edit#slide=id.g4ef91f4242_0_9

Et svg ici : https://drive.google.com/drive/u/0/folders/10JkM0dP8NrikKuKT2JnihKRDNaurP-u_

**Comment by margot-sanchez** [comment]
Erreur sur le lien covoiturage.beta.gouv.fr qui n'est pas encore https

**Comment by samueleyre** [comment]
Corrigé en local, en attente du deploiement sur netlify pour tester

**Comment by margot-sanchez** [comment]
Done sur Scalingo
