### ISSUE TITLE
Fonctionnalité upload de trajet au format CSV

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage-dashboard#33]
Estimation : 3h

**Comment by jonathanfallon** [comment]
Back modifié pour ne plus avoir de spécificités opérateurs et améliorer le retour d'erreurs. Front modifié pour mieux afficher les erreurs.

**Comment by jonathanfallon** [comment]
@margot-sanchez 
Procédure de test :
    Dans Général > Import: Choisir un opérateur
    Uploader le fichier CSV
    Vérifier que les erreurs s'affichent bien

Fichier buggué : https://framadrop.org/r/JJnXxuetIv#EETwDpfAx1dBKgzQPUudoSry/8Lm43IR5uuJlbZU38A=
Fichier bon : https://framadrop.org/r/cvICkv4na9#RP/dNtE5XmtFka39AORGmxRWZ5BCtPS9MH+nDpiHJ7w=

**Comment by margot-sanchez** [comment]
Test validé : mettre une autre classe que A, B ou C

**Comment by margot-sanchez** [comment]
Test incohérent : j'ai alimenté le compte de OuiHop avec un CSV comprenant clairement Karos comme opérateur en colonne B.

**Comment by margot-sanchez** [comment]
Teste validé : J'ai alimenté le registre avec des numéros de téléphone en +334 au lieu de +336 ou +337 👍

**Comment by margot-sanchez** [comment]
Test validé : J'ai alimenté le registre avec uniquement les adresses "litérales" + codes INSEE 👍

**Comment by margot-sanchez** [comment]
Test validé : Tentative d'alimenter le registre avec un trajet 100% différent mis à part le numéro du trajet. Le registre a détecté qu'il s'agissait du même ID. 👍

**Comment by margot-sanchez** [comment]
Test incohérent : J'ai alimenté le registre avec un nom d'opérateur Dédé covoit dans la colonne B qui n'était pas existant dans la base. 👎

**Comment by margot-sanchez** [comment]
Test incohérent (amélioration détection fraude) : J'ai alimenté le registre avec un conducteur et passager ayant le même numéro de téléphone 👎

**Comment by margot-sanchez** [comment]
Test validé : Tentative d'alimenter le registre avec des trajets sans lat/long ou Insee ou literal sur le conducteur 👍

**Comment by margot-sanchez** [comment]
Test validé : Tentative d'alimenter le registre avec des trajets sans lat/long ou Insee ou literal sur le passager 👍
