### ISSUE TITLE
Fonctionnalité download prenant en compte les filtres appliqués

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage-dashboard#36]
Ajout d'un header "Accept: text/csv" sans param limit/offset

Estimation 2h

**Comment by margot-sanchez** [comment]
@jonathanfallon on est toujours en attente du back ou pas ?

**Comment by jonathanfallon** [comment]
duplicate #15

**Comment by jonathanfallon** [comment]
C'est implémenté (cf [issue 15](https://github.com/betagouv/preuve-covoiturage-api/issues/15) dans le back).

Il faut envoyer un Header `Accept: text/csv` dans la requête pour récupérer un flux CSV de toutes les entrées. Les filtres fonctionnent comme pour les requêtes JSON (`filter, limit, sort, skip, projection`) mais `limit` est _limité_ à un maximum de 1000 entrées.

Le fichier est généré avec un Mime type `text/csv;encoding=utf8` qui est à tester avec Excel qui semble préférer `application/vnd.ms-excel` mais qui n'est pas standard.

**Comment by jonathanfallon** [comment]
Note : Voir https://davidburgos.blog/export-csv-with-correct-charset-in-nodejs/ pour le Content-type si ça ne fonctionne pas avec Excel

**Comment by jonathanfallon** [comment]
Cacher les données personnelles mais afficher le max de données géolocalisées.
