### ISSUE TITLE
Variable âge - majeur / mineur / nc (non communiquée)

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage-dashboard#63]
Ne pas partir du principe que lorsque l'âge n'est pas demandé, il s'agit forcement d'un mineur. Sur des opérateurs l'âge n'est pas forcement demandé.

@jonathanfallon cela change aussi de manière mineure le schéma de données en back ?
Mais pour l'instant sur les opérateurs que l'on a ils ont tous l'information ou pas ? Est-ce qu'on attend d'avoir un opérateur qui ne demande pas avant de mettre à jour.
 
Mettre à jour ici également : https://registre-preuve-de-covoiturage.gitbook.io/produit/api/schema-json

**Comment by jonathanfallon** [comment]
Le back accepte les valeurs : 
- `true` : majeur
- `false` : mineur
- `null` : nc

**Comment by margot-sanchez** [comment]
Are we still waiting for the back ?

**Comment by jonathanfallon** [comment]
On est en `null` par défaut et la doc est mise à jour.
