### ISSUE TITLE
Gestion des erreurs CORS

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage-dashboard#64]
l'API restreint les appels via CORS à l'URL donnée par `APP_URL` dans la config.
Les erreurs ne sont pas explicites dans le front. Quelle solution peut-on avoir pour que ce soit clair que le front n'est pas sur le bon domaine ?

**Comment by nmrgt** [comment]
Je pense qu'on s'en fout :)
Le cas d'usage est quelqu'un qui clone le dépôt pour se brancher sur l'API donc bon....
