### ISSUE TITLE
Autofill des infos utilisateur dans le formulaire d'édition

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage-dashboard#84]

**Comment by margot-sanchez** [comment]
Enlever la possibilité de voir le mot de passe des autres utilisateurs (quand on est admin) :)

**Comment by margot-sanchez** [comment]
Lorsque je me connecte en tant que super administrateur j'ai désormais la possibilité de changer les mots de passe des autres utilisateurs. 👍 

Mais le fait de voir un champs "mot de passe" lance automatiquement mon gestionnaire de mot de passe : 
![image](https://user-images.githubusercontent.com/15428433/55334332-54be5500-5499-11e9-9d43-58a9eab7e97c.png)
C'est un problème spécifique à moi si ça se trouve. J'ai le gestionnaire de mot de passe de Google.

**Comment by jonathanfallon** [comment]
Ressources :
- https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
- https://www.chromium.org/developers/design-documents/create-amazing-password-forms
- https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill
- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by jonathanfallon** [comment]
PR #117
